// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCff0ix4ZO7q1kUausbijgR6uPhhKo5_A0',
    appId: '1:392597284783:web:a11ae66f1dfc983fb3b15a',
    messagingSenderId: '392597284783',
    projectId: 'mobilproje-f53ad',
    authDomain: 'mobilproje-f53ad.firebaseapp.com',
    storageBucket: 'mobilproje-f53ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkdcn7CXu4dO8OjlmQatOejayMtAUg8E',
    appId: '1:392597284783:android:b56caee703850a7ab3b15a',
    messagingSenderId: '392597284783',
    projectId: 'mobilproje-f53ad',
    storageBucket: 'mobilproje-f53ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvG01gUmr5kdijurosUpTqbLWm463oYpw',
    appId: '1:392597284783:ios:6cd453ef93ce873db3b15a',
    messagingSenderId: '392597284783',
    projectId: 'mobilproje-f53ad',
    storageBucket: 'mobilproje-f53ad.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvG01gUmr5kdijurosUpTqbLWm463oYpw',
    appId: '1:392597284783:ios:6cd453ef93ce873db3b15a',
    messagingSenderId: '392597284783',
    projectId: 'mobilproje-f53ad',
    storageBucket: 'mobilproje-f53ad.firebasestorage.app',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCff0ix4ZO7q1kUausbijgR6uPhhKo5_A0',
    appId: '1:392597284783:web:a78f14c43304be4ab3b15a',
    messagingSenderId: '392597284783',
    projectId: 'mobilproje-f53ad',
    authDomain: 'mobilproje-f53ad.firebaseapp.com',
    storageBucket: 'mobilproje-f53ad.firebasestorage.app',
  );
}
